version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Node.js dependencies..."
      - npm ci  # Or npm install, if you prefer

  build:
    commands:
      - echo "Installing Maven dependencies (skipping tests)..."
      - mvn clean install -DskipTests -U
      - echo "Running Appium tests..."
      - npm test  # This runs your test suite targeting the cloud provider

artifacts:
  files:
    - 'results/**/*'  # Adjust if your test outputs go somewhere else
  discard-paths: yes
